### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by frammkor** [benface/tailwindcss-interaction-variants#14]
```
Could not find a declaration file for module 'tailwindcss-interaction-variants'. '.../node_modules/tailwindcss-interaction-variants/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/tailwindcss-interaction-variants` if it exists or add a new declaration (.d.ts) file containing `declare module 'tailwindcss-interaction-variants';`ts(7016)
```

This errors when traying 
```
	plugins: [
		require('tailwindcss-interaction-variants'),
```

So I cannot use this package.

I would appreciate the help.

**Comment by benface** [comment]
Hey @frammkor! This looks like a TypeScript issue. This project doesn't use TypeScript so I'm afraid I cannot help. Also, I just deprecated this plugin since Tailwind's JIT engine (which is the _only_ engine in Tailwind 3.0) supports every possible interaction variant and more.
