### ISSUE TITLE
Add `checked`?

### ISSUE THREAD

**Issue by benface** [benface/tailwindcss-interaction-variants#4]
Is it an "interaction variant"?

What about `required`, `read-only`, `valid`, and `invalid`?

**Comment by benface** [comment]
Hold on: https://github.com/tailwindcss/tailwindcss/pull/1285

**Comment by GeoffSelby** [comment]
I think 1.2 is pretty much set in stone so my PR for the checked variant most likely won’t be added until 1.3 or later. If you want to add it here it might be a good idea.
